package com.example.accessingdatamysql.controller;

import com.example.accessingdatamysql.entity.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.access.prepost.PreAuthorize;
// import org.springframework.http.*;
import org.springframework.web.bind.annotation.*;

// import java.sql.Timestamp;
import java.util.*;

// import javax.validation.constraints.Null;

import com.example.accessingdatamysql.service.CardService;

@CrossOrigin(origins = "*")
@RestController // This means that this class is a Controller
@RequestMapping(path = "/card") // This means URL's start with /demo (after Application path)
public class CardController {
  @Autowired // This means to get the bean called CardRepository
  // Which is auto-generated by Spring, we will use it to handle the data
  private CardService CardService;

  @RequestMapping(value = "/getCard")
  public Card findCardByCardId(@RequestParam("cardId") Integer cardId) {
    return CardService.getOneCard(cardId);
  }

  @RequestMapping(value = "/addCard")
  public @ResponseBody Card addNewCard(@RequestBody Card newCard) {
    return CardService.addNewCard(newCard);
  }

  @RequestMapping(value = "/updateCard")
  @PreAuthorize("hasRole('ROLE_ADMIN')")
  public @ResponseBody Card updateCard(@RequestBody Card updateCard) {
    // System.out.println("In controller");

    return CardService.updateCard(updateCard);
  }

  @RequestMapping(value = "/getAllCards")
  public List<Card> getAllCards() {
    return CardService.getAllCards();
  }

  @RequestMapping(value = "/deleteCards")
  @PreAuthorize("hasRole('ROLE_ADMIN')")
  public String deleteCards(@RequestParam("cardIds") List<Integer> cardIds) {
    return CardService.deleteCards(cardIds);
  }

  @RequestMapping(value = "/deleteAllCards")
  @PreAuthorize("hasRole('ROLE_ADMIN')")
  public String deleteAll() {
    return CardService.deleteAll();
  }

  @RequestMapping(value = "/deleteCard")
  @PreAuthorize("hasRole('ROLE_ADMIN')")
  public List<Card> deleteCard(@RequestParam("cardId") Integer cardId) {
    return CardService.deleteCard(cardId);
  }

}
