package com.example.accessingdatamysql.controller;

// import com.example.accessingdatamysql.entity.*;
import org.springframework.beans.factory.annotation.Autowired;
// import org.springframework.http.*;
import org.springframework.web.bind.annotation.*;

// import java.sql.Timestamp;
// import java.util.*;

// import javax.validation.constraints.Null;

import com.example.accessingdatamysql.service.*;

@CrossOrigin(origins = "*")
@RestController // This means that this class is a Controller
@RequestMapping(path = "/mechanism") // This means URL's start with /demo (after Application path)
public class MechanismController {
  @Autowired // This means to get the bean called MechanismRepository
  // Which is auto-generated by Spring, we will use it to handle the data
  private MechanismService mechanismService;

  // 抽卡逻辑在这里
  @RequestMapping(value = "/drawCard")
  public Integer drawCard(@RequestParam("chi") Integer chi, @RequestParam("mat") Integer mat,
      @RequestParam("eng") Integer eng) {
    return mechanismService.drawCard(chi, mat, eng);
  }

}
