package com.example.accessingdatamysql.controller;

import com.example.accessingdatamysql.entity.*;
import org.springframework.beans.factory.annotation.Autowired;
// import org.springframework.http.*;
import org.springframework.web.bind.annotation.*;

// import java.sql.Timestamp;
import java.util.*;

// import javax.validation.constraints.Null;

import com.example.accessingdatamysql.service.MissionService;

@CrossOrigin(origins = "*")
@RestController // This means that this class is a Controller
@RequestMapping(path = "/mission") // This means URL's start with /demo (after Application path)
public class MissionController {
  @Autowired // This means to get the bean called MissionRepository
  // Which is auto-generated by Spring, we will use it to handle the data
  private MissionService MissionService;

  @RequestMapping(value = "/getMission")
  public Mission findMissionByMissionId(@RequestParam("missionId") Integer MissionId) {
    return MissionService.getOneMission(MissionId);
  }

  @RequestMapping(value = "/addMission")
  public @ResponseBody String addNewMission(@RequestParam("type") String type,
      @RequestParam("missionName") String MissionName, @RequestParam("missionDescription") String MissionDescription,
      @RequestParam("awardItemIds") List<Integer> awardItemIds) {
    return MissionService.addNewMission(type, MissionName, MissionDescription, awardItemIds);
  }

  @RequestMapping(value = "/updateMission")
  public @ResponseBody String updateMission(@RequestParam("missionId") Integer MissionId,
      @RequestParam("type") String type, @RequestParam("missionName") String MissionName,
      @RequestParam("missionDescription") String MissionDescription,
      @RequestParam("awardItemIds") List<Integer> awardItemIds) {
    return MissionService.updateMission(MissionId, type, MissionName, MissionDescription, awardItemIds);
  }

  @RequestMapping(value = "/getAllMissions")
  public List<Mission> getAllMissions() {
    return MissionService.getAllMissions();
  }

  @RequestMapping(value = "/deleteMissions")
  public String deleteMissions(@RequestParam("missionIds") List<Integer> MissionIds) {
    return MissionService.deleteMissions(MissionIds);
  }

  @RequestMapping(value = "/deleteAllMissions")
  public String deleteAll() {
    return MissionService.deleteAll();
  }

  @RequestMapping(value = "/deleteMission")
  public List<Mission> deleteMission(@RequestParam("missionId") Integer MissionId) {
    return MissionService.deleteMission(MissionId);
  }
}
